name: Continuous Integration 
on: [push,pull_request]
jobs:
  build_prod:
    name: Build_Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Master Branch
  build_dev:
    name: Build_Dev
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/hotfix'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Hotfix Branch

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_prod
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
