name: Continuous Integration 
on: [push, pull_request]
jobs:
  build_prod:
    name: Build_Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Master Branch
  build_dev:
    name: Build_Dev
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/hotfix'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Hotfix Branch

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_prod
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: build artifacts
        run: make build-linux && make build-windows && make build-darwin
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
          asset_name: azblogfilter.linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/azblogfilter.darwin-amd64.tar.gz
          asset_name: azblogfilter.darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/azblogfilter.windows-amd64.zip
          asset_name: azblogfilter.windows-amd64.zip
          asset_content_type: application/zip
