name: Continuous Integration 
on: [push, pull_request]
jobs:
  build_prod:
    name: Build_Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Master Branch
  build_dev:
    name: Build_Dev
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/hotfix'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Hotfix Branch

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_prod
    steps:
      - uses: actions/checkout@master
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'
          update_existing: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
