name: Continuous Integration 
on: [push, pull_request]
jobs:
  build_prod:
    name: Build_Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Master Branch
  build_dev:
    name: Build_Dev
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/hotfix'}}
    steps:
      - name: Install yarn
        uses: actions/checkout@v1
      - run: echo Hello World Hotfix Branch

  release:
    name: Create Release
    if: ${{needs.build_dev.outputs=='success' || needs.build_prod.outputs=='success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
