name: Test release version
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: "${{ secrets.ROBOT_TOKEN }}"
        with:
          publish_latest_tag: true



