jobs:
  build:
    name: Build, Test, Pack, Push
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn
        run: npm install -g yarn
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/hotf
