name: Continuous Integration Workflow
on: [push, pull_request]
jobs:
  build:
    name: Build, Test, Pack, Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/masters'}}
    steps:
      - name: Install yarn
        run: npm install -g yarn
 
