name: .NET Core
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        run: |
          dotnet build -c Release
          zip -r binaries.zip ./MyProject/bin/release/netcoreapp3.1
          zip -r otherstuff.zip ./otherstuff
          
      # Get the assembly version, use this as the tag.
      # That way, to do a new release, just update the assembly version on the next commit
      - name: Get Assembly Version
        id: get_version
        uses: jasondavis303/net-sdk-proj-file-version@v1.0.1
        with: 
          PROJ_FILE: MyProject/MyProject.csproj        
      
      - name: Tag and Release
        uses: jasondavis303/tag-and-release-and-upload@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Use the version from the previous step
          version: v${{ steps.get_version.outputs.ASSEMBLY_VERSION }}
          
          assets: '[ "binaries.zip", "otherstuff.zip" ]'
          overwrite: false          
